docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/0mut_300wt_1freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/0mut_300wt_1freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 0mut_300wt_1freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/0mut_300wt_2freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/0mut_300wt_2freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 0mut_300wt_2freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/0mut_300wt_3freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/0mut_300wt_3freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 0mut_300wt_3freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/0mut_300wt_4freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/0mut_300wt_4freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 0mut_300wt_4freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/100mut_200wt_1freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/100mut_200wt_1freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 100mut_200wt_1freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/100mut_200wt_2freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/100mut_200wt_2freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 100mut_200wt_2freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/100mut_200wt_3freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/100mut_200wt_3freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 100mut_200wt_3freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/100mut_200wt_4freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/100mut_200wt_4freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 100mut_200wt_4freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/200mut_100wt_1freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/200mut_100wt_1freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 200mut_100wt_1freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/200mut_100wt_2freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/200mut_100wt_2freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 200mut_100wt_2freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/200mut_100wt_3freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/200mut_100wt_3freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 200mut_100wt_3freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/200mut_100wt_4freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/200mut_100wt_4freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 200mut_100wt_4freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/270mut_30wt_1freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/270mut_30wt_1freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 270mut_30wt_1freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/270mut_30wt_2freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/270mut_30wt_2freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 270mut_30wt_2freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/270mut_30wt_3freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/270mut_30wt_3freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 270mut_30wt_3freq_150readlen -p 4 --window_around_sgrna 5
docker run -v ${PWD}:/home/ai/Projects/amplican_manuscript/analysis -w /home/ai/Projects/amplican_manuscript/analysis -i pinellolab/crispresso2 CRISPRessoPooled -r1 ./indel_size/simulation/merged/270mut_30wt_4freq_150readlen_sim1.fq -r2 ./indel_size/simulation/merged/270mut_30wt_4freq_150readlen_sim2.fq -f ./indel_size/simulation/merged/crispresso_pooled_amplicons.txt -x ./idx/danRer7.fa --name 270mut_30wt_4freq_150readlen -p 4 --window_around_sgrna 5

sudo chmod -R 777 CRISPRessoPooled_on_*
mv CRISPRessoPooled_on_* ./indel_size/simulation/crispresso2/pooled/
